### ISSUE TITLE
How to connect to the client?

### ISSUE THREAD

**Issue by seanknox** [Microsoft/PartsUnlimitedMRPmicro#21]
Deploying the client yields a default Tomcat page. What am I missing?

**Comment by dtzar** [comment]
It's possible you're not missing anything - it might be broken :(

**Comment by julienstroheker** [comment]
@seanknox did you try to add « /mrp » in the path ?

**Comment by seanknox** [comment]
I did not! Will try that.
________________________________

**Comment by lalo** [comment]
@seanknox The endpoint is at `/mrp_client/` which is the name of the WAR produced.

**Comment by dtzar** [comment]
Just verified - @lalo is correct.  It is served up on the `/mrp_client/` URL.  I'm adding as a note to the readme.
